# Generated by Django 4.1 on 2022-08-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentname',
            options={'managed': False, 'verbose_name_plural': 'Agent Names'},
        ),
        migrations.AlterModelOptions(
            name='announcedlgaresults',
            options={'managed': False, 'verbose_name_plural': 'Announced LGA Results'},
        ),
        migrations.AlterModelOptions(
            name='announcedpuresults',
            options={'managed': False, 'verbose_name_plural': 'Announced Pu Results'},
        ),
        migrations.AlterModelOptions(
            name='announcedstateresults',
            options={'managed': False, 'verbose_name_plural': 'Announced State Results'},
        ),
        migrations.AlterModelOptions(
            name='announcedwardresults',
            options={'managed': False, 'verbose_name_plural': 'Announced Ward Results'},
        ),
        migrations.AlterModelOptions(
            name='lga',
            options={'managed': False, 'verbose_name_plural': 'Local Govt Areas'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'managed': False, 'verbose_name_plural': 'Political Parties'},
        ),
        migrations.AlterModelOptions(
            name='pollingunit',
            options={'managed': False, 'verbose_name_plural': 'Polling Units'},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'managed': False, 'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'managed': False, 'verbose_name_plural': 'Wards'},
        ),
    ]
